### ISSUE TITLE
ALPN is not configured properly - unable to connect on Windows 10 32bit, JRE 8

### ISSUE THREAD

**Issue by jeffersonatsafe** [olavloite/spanner-jdbc#28]
Hello, 

We tried using the driver under a 32-bit environment, but we're getting this error instead: 
```
java.lang.IllegalArgumentException: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting for more information.
	at nl.topicus.jdbc.shaded.io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:163)
	at nl.topicus.jdbc.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
	at nl.topicus.jdbc.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
	at nl.topicus.jdbc.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerOptions$NettyRpcChannelFactory.newSslContext(SpannerOptions.java:311)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerOptions$NettyRpcChannelFactory.newChannel(SpannerOptions.java:299)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerOptions.createChannel(SpannerOptions.java:272)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerOptions.createChannels(SpannerOptions.java:259)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerOptions.<init>(SpannerOptions.java:92)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerOptions.<init>(SpannerOptions.java:45)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerOptions$Builder.build(SpannerOptions.java:195)
	at nl.topicus.jdbc.CloudSpannerConnection.<init>(CloudSpannerConnection.java:183)
	at nl.topicus.jdbc.CloudSpannerDriver.connect(CloudSpannerDriver.java:275)
	at COM.safe.fme.jdbc.JdbcCommon.openConnection(JdbcCommon.java:469)
	at COM.safe.fme.jdbc.JdbcReader.openHelper(JdbcReader.java:192)
	at COM.safe.fme.jdbc.JdbcReader.open(JdbcReader.java:162)
Caused by: java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at nl.topicus.jdbc.shaded.io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:34)
	at nl.topicus.jdbc.shaded.io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:153)
	... 15 more
```

This was on a Windows 10 machine, running on 32-bit configuration, with Java 8
Driver version: 0.23

Note that we've had no problems connecting in 64-bit. 

We've done a bit of digging, and seems that there are reports of similar problems here:
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2740
and here:
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2813

would upgrading google-cloud-spanner dependency fix this?

**Comment by olavloite** [comment]
Driver version 0.23 already includes version 0.33.0-beta of Google Cloud Spanner libraries, which is the one referenced in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2740. The problem is that the Google Cloud Spanner library, and thereby also the JDBC driver, only include 64-bit versions of the netty_tcnative libraries.
Have a look in the netty-tcnative-boringssl-static-2.0.7.Final.jar that is included by the Google Cloud Spanner. The native libraries are situated in the META-INF/native of the jar, and as you can see it only includes 64 bit versions. I'm afraid this is an undocumented (?) prerequisite to use this library.

I'll try to have a look this weekend if there is any way to work around this, but I don't have very high hopes...

**Comment by olavloite** [comment]
[spanner-jdbc-0.26-SNAPSHOT.zip](https://github.com/olavloite/spanner-jdbc/files/1777379/spanner-jdbc-0.26-SNAPSHOT.zip)

**Comment by jpoernomoatsafe** [comment]
I just gave this a try... but still getting the same exceptions
