### ISSUE TITLE
Need support for PreparedStatement.getParameterMetaData()

### ISSUE THREAD

**Issue by ravenAtSafe** [olavloite/spanner-jdbc#4]
When invoking getParameterMetaData() on an INSERT PreparedStatement an exception is thrown.

**Comment by ravenAtSafe** [comment]
```
Exception in thread "main" 
COM.safe.fme.TranslationFailureException: java.sql.SQLFeatureNotSupportedException
	at COM.safe.fme.JdbcWriter.bindValues(JdbcWriter.java:740)

	at COM.safe.fme.JdbcWriter.insertFeature(JdbcWriter.java:614)
	at COM.safe.fme.JdbcWriter.writeFeature(JdbcWriter.java:573)
	at COM.safe.fme.JdbcWriter.write(JdbcWriter.java:286)

Caused by: java.sql.SQLFeatureNotSupportedException
	at nl.topicus.jdbc.statement.AbstractCloudSpannerPreparedStatement.getParameterMetaData(AbstractCloudSpannerPreparedStatement.java:244)
	at COM.safe.fme.JdbcWriter.bindValues(JdbcWriter.java:734)

	... 3 more

COM.safe.fme.TranslationFailureException: java.sql.SQLFeatureNotSupportedException
COM.safe.fme.TranslationFailureException: java.sql.SQLFeatureNotSupportedException
Destination Feature Type Routing Correlator(RoutingFactory): COM.safe.fme.TranslationFailureException: java.sql.SQLFeatureNotSupportedException
Exception in thread "main" java.sql.SQLFeatureNotSupportedException

	at nl.topicus.jdbc.statement.AbstractCloudSpannerStatement.clearBatch(AbstractCloudSpannerStatement.java:238)
	at nl.topicus.jdbc.statement.CloudSpannerStatement.clearBatch(CloudSpannerStatement.java:22)
	at COM.safe.fme.JdbcWriter.rollbackTransaction(JdbcWriter.java:1670)
	at COM.safe.fme.JdbcWriter.abort(JdbcWriter.java:210)

```

**Comment by olavloite** [comment]
As of version 0.6 this method does no longer throw a SQLFeatureNotSupportedException, but returns parameter metadata based on the SQL String of the PreparedStatement and the values already supplied by the user. It does not access the database to retrieve metadata.
