### ISSUE TITLE
Exception during commit after setting java.sql.timestamp to insert statement

### ISSUE THREAD

**Issue by jpoernomoatsafe** [olavloite/spanner-jdbc#53]
Hello Knut!

We've run into a bit of a problem when trying to `setTimestamp` on an insert statement. 

Table schema is as follows:
myint INT64, Primary Key
mydate DATE

statement:
INSERT INTO `jpoetestdest` (`mydate`, `myint`) VALUES (?, ?)

code (roughly):
```
Connection connection = getConnection();
PreparedStatement statement = connection.prepareStatement("INSERT INTO `jpoetestdest` (`mydate`, `myint`) VALUES (?,?);
java.sql.Timestamp mydate = new Timestamp(1514793600000L);
statement.setTimestamp(0, mydate);`
statement.setInt(1, 1);
statement.execute();
connection.commit();
```

We'll get this exception: 

```
nl.topicus.jdbc.exception.CloudSpannerSQLException: COMMIT failed: FAILED_PRECONDITION: nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Invalid value for column mydate in table jpoetestdest: Expected DATE.
	at nl.topicus.jdbc.transaction.TransactionThread.stopTransaction(TransactionThread.java:280)
	at nl.topicus.jdbc.transaction.TransactionThread.commit(TransactionThread.java:209)
	at nl.topicus.jdbc.transaction.CloudSpannerTransaction.commit(CloudSpannerTransaction.java:99)
	at nl.topicus.jdbc.CloudSpannerConnection.commit(CloudSpannerConnection.java:443)
	at COM.safe.fme.jdbc.JdbcWriter.commitTransaction(JdbcWriter.java:656)
	at COM.safe.fme.jdbc.JdbcWriter.close(JdbcWriter.java:193)
Caused by: nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerException: FAILED_PRECONDITION: nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Invalid value for column mydate in table jpoetestdest: Expected DATE.
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:119)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:43)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:80)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.spi.v1.GrpcSpannerRpc.get(GrpcSpannerRpc.java:429)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.spi.v1.GrpcSpannerRpc.commit(GrpcSpannerRpc.java:401)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$TransactionContextImpl$1.call(SpannerImpl.java:1358)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$TransactionContextImpl$1.call(SpannerImpl.java:1355)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl.runWithRetries(SpannerImpl.java:227)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$TransactionContextImpl.commit(SpannerImpl.java:1354)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$TransactionRunnerImpl.runInternal(SpannerImpl.java:1248)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$TransactionRunnerImpl.run(SpannerImpl.java:1192)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SessionPool$PooledSession$1.run(SessionPool.java:334)
	at nl.topicus.jdbc.transaction.TransactionThread.run(TransactionThread.java:102)
Caused by: java.util.concurrent.ExecutionException: nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Invalid value for column mydate in table jpoetestdest: Expected DATE.
	at nl.topicus.jdbc.shaded.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
	at nl.topicus.jdbc.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:479)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.spi.v1.GrpcSpannerRpc.get(GrpcSpannerRpc.java:423)
	... 9 more
Caused by: nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Invalid value for column mydate in table jpoetestdest: Expected DATE.
	at nl.topicus.jdbc.shaded.io.grpc.Status.asRuntimeException(Status.java:526)
	at nl.topicus.jdbc.shaded.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
	at nl.topicus.jdbc.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100)
	at nl.topicus.jdbc.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at nl.topicus.jdbc.shaded.com.google.cloud.spanner.spi.v1.WatchdogInterceptor$MonitoredCall$1.onClose(WatchdogInterceptor.java:190)
	at nl.topicus.jdbc.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at nl.topicus.jdbc.shaded.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at nl.topicus.jdbc.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at nl.topicus.jdbc.shaded.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
	at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
	at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
	at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
	at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
	at nl.topicus.jdbc.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at nl.topicus.jdbc.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

is this an issue? 
Thanks!

**Comment by olavloite** [comment]
Hi,

No, this is expected behavior. Cloud Spanner makes a distinction between the data types DATE and TIMESTAMP. The former does not allow any time information to be stored, while the latter does. Your table definition contains a DATE column, while your input is a java.sql.Timestamp that translates into a Cloud Spanner TIMESTAMP value. Either change your data model into using a TIMESTAMP, or change your Java code to use a java.sql.Date value.
