### ISSUE TITLE
Transaction aborted

### ISSUE THREAD

**Issue by minhdqvn** [olavloite/spanner-jdbc#64]
It happen after a duration of time. I assume that my app gets idle transaction that will be aborted after a wait of time. How can I reuse the connection without retrying.

**Comment by minhdqvn** [comment]
@olavloite This is the log I got, I have only run query with 30 CU.
`Caused by: org.hibernate.exception.GenericJDBCException: could not execute query
       at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.loader.Loader.doList(Loader.java:2620) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.loader.Loader.doList(Loader.java:2600) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.loader.Loader.list(Loader.java:2424) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:501) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:371) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1326) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.internal.QueryImpl.list(QueryImpl.java:87) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606) ~[hibernate-entitymanager-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483) ~[hibernate-entitymanager-5.0.12.Final.jar:5.0.12.Final]
       at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(JpaQueryExecution.java:186) ~[spring-data-jpa-1.11.4.RELEASE.jar:na]
       at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:85) ~[spring-data-jpa-1.11.4.RELEASE.jar:na]
       at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:116) ~[spring-data-jpa-1.11.4.RELEASE.jar:na]
       at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:106) ~[spring-data-jpa-1.11.4.RELEASE.jar:na]
       at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:483) ~[spring-data-commons-1.13.4.RELEASE.jar:na]
       at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461) ~[spring-data-commons-1.13.4.RELEASE.jar:na]
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
       at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56) ~[spring-data-commons-1.13.4.RELEASE.jar:na]
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
       at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.9.RELEASE.jar:4.3.9.RELEASE]
       at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282) ~[spring-tx-4.3.9.RELEASE.jar:4.3.9.RELEASE]
       at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.9.RELEASE.jar:4.3.9.RELEASE]
       at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.9.RELEASE.jar:4.3.9.RELEASE]
       at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.3.9.RELEASE.jar:4.3.9.RELEASE]
       ... 168 common frames omitted
Caused by: nl.topicus.jdbc.exception.CloudSpannerSQLException: ABORTED: Aborted due to transient fault
retry_delay {
}
 
       at nl.topicus.jdbc.resultset.CloudSpannerResultSet.next(CloudSpannerResultSet.java:125) ~[spanner-jdbc-1.0.8.jar:na]
       at org.hibernate.loader.Loader.processResultSet(Loader.java:968) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.loader.Loader.doQuery(Loader.java:930) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       at org.hibernate.loader.Loader.doList(Loader.java:2617) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
       ... 192 common frames omitted
Caused by: nl.topicus.jdbc.shaded.com.google.cloud.spanner.AbortedException: ABORTED: Aborted due to transient fault
retry_delay {
}
 
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:117) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:71) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:58) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$GrpcStreamIterator.computeNext(SpannerImpl.java:2331) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$GrpcStreamIterator.computeNext(SpannerImpl.java:2277) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$ResumableStreamIterator.computeNext(SpannerImpl.java:2425) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$ResumableStreamIterator.computeNext(SpannerImpl.java:2374) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$GrpcValueIterator.ensureReady(SpannerImpl.java:2589) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$GrpcValueIterator.getMetadata(SpannerImpl.java:2562) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerImpl$GrpcResultSet.next(SpannerImpl.java:1859) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.resultset.CloudSpannerResultSet.next(CloudSpannerResultSet.java:121) ~[spanner-jdbc-1.0.8.jar:na]
       ... 196 common frames omitted
Caused by: nl.topicus.jdbc.shaded.com.google.cloud.spanner.AbortedException: ABORTED: Aborted due to transient fault
retry_delay {
}
 
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:117) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:43) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:80) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.spi.v1.GrpcSpannerRpc$ResultSetStreamObserver.onError(GrpcSpannerRpc.java:578) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.com.google.cloud.spanner.spi.v1.WatchdogInterceptor$MonitoredCall$1.onClose(WatchdogInterceptor.java:190) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[spanner-jdbc-1.0.8.jar:na]
       at nl.topicus.jdbc.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[spanner-jdbc-1.0.8.jar:na]
       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_171]
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_171]
       ... 1 common frames omitted
Caused by: nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: ABORTED: Aborted due to transient fault
retry_delay {
}
 
       at nl.topicus.jdbc.shaded.io.grpc.Status.asRuntimeException(Status.java:526) ~[spanner-jdbc-1.0.8.jar:na]
       ... 19 common frames omitted
 
2018-06-15 16:43:54.164 DEBUG 5224 --- [io-9003-exec-49] o.s.web.servlet.DispatcherServlet        : Could not complete request`

**Comment by minhdqvn** [comment]
It seem related to getting data in read-write transaction. I got the same issue such as this link [https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2176]. So this should be closed.
