### ISSUE TITLE
CCJSqlParser error

### ISSUE THREAD

**Issue by flascaray** [olavloite/spanner-jdbc#82]
When I make a native query I get the following error:

```java
@Query(nativeQuery = true, value = "SELECT n.news_type_id, n.text FROM news2 AS n INNER JOIN news_types nt ON (nt.news_type_id = n.news_type_id) "
			+ "WHERE n.seeker_id = :seekerId "
			+ "AND TIMESTAMP_ADD(n.created, INTERVAL nt.update_hours HOUR) > CURRENT_TIMESTAMP() "
			+ "AND nt.enabled = true "
			+ "ORDER BY nt.priority DESC "
			+ "LIMIT 1 ")
Map<String, String> findBySeekerId(@Param("seekerId") String seekerId);
```
```java
Caused by: nl.topicus.jdbc.shaded.net.sf.jsqlparser.parser.ParseException: Encountered " "(" "( "" at line 1, column 149.
Was expecting one of:
    <EOF> 
    "AND" ...
    "FOR" ...
    "UNION" ...
    "GROUP" ...
    "ORDER" ...
    "HAVING" ...
    "INTERSECT" ...
    "EXCEPT" ...
    "MINUS" ...
    "START" ...
    "CONNECT" ...
    ";" ...
    "ORDER" ...
    "ORDER" ...
    
	at nl.topicus.jdbc.shaded.net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:16869)
	at nl.topicus.jdbc.shaded.net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:16722)
	at nl.topicus.jdbc.shaded.net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:91)
	at nl.topicus.jdbc.shaded.net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:54)
	... 128 common frames omitted
```

If i comment the following line it's work
```
"AND TIMESTAMP_ADD(n.created, INTERVAL nt.update_hours HOUR) > CURRENT_TIMESTAMP() "
```

**Comment by olavloite** [comment]
Fixed for version 1.0.10

**Comment by flascaray** [comment]
Hi @olavloite now i have the following error. With version 1.0.10 and the same query. 

```java
@Query(nativeQuery = true, value = "SELECT n.news_type_id, n.text FROM news AS n INNER JOIN news_types nt ON (nt.news_type_id = n.news_type_id) "
			+ "WHERE n.seeker_id = :seekerId "
			+ "AND TIMESTAMP_ADD(n.created, INTERVAL nt.update_hours HOUR) > CURRENT_TIMESTAMP() "
			+ "AND nt.enabled = true "
			+ "ORDER BY nt.priority DESC "
			+ "LIMIT 1 ")
	Map<String, String> findBySeekerId(@Param("seekerId") String seekerId);
```
The problem is something with **nt.update_hours**

```java
java.lang.NullPointerException: null
	at nl.topicus.jdbc.resultset.CloudSpannerResultSetMetaData.getAlias(CloudSpannerResultSetMetaData.java:384)
	at nl.topicus.jdbc.resultset.CloudSpannerResultSetMetaData.getColumnLabel(CloudSpannerResultSetMetaData.java:352)
	at org.hibernate.dialect.ColumnAliasExtractor$1.extractColumnAlias(ColumnAliasExtractor.java:39)
	at org.hibernate.loader.custom.JdbcResultMetadata.getColumnName(JdbcResultMetadata.java:59)
	at org.hibernate.loader.custom.ScalarResultColumnProcessor.performDiscovery(ScalarResultColumnProcessor.java:39)
	at org.hibernate.loader.custom.CustomLoader.autoDiscoverTypes(CustomLoader.java:482)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:2214)
```

Thanks.

**Comment by olavloite** [comment]
This problem is caused by the same issue as in #86
