### ISSUE TITLE
NullPointerException when run query

### ISSUE THREAD

**Issue by flascaray** [olavloite/spanner-jdbc#86]
Hi @olavloite, I have the following error when using a dynamic INTERVAL query. 

```sql
SELECT * FROM news_types WHERE TIMESTAMP_ADD(news_start, INTERVAL update_hours HOUR) > CURRENT_TIMESTAMP(); 
```
```java
Caused by: java.lang.NullPointerException
	at nl.topicus.jdbc.resultset.CloudSpannerResultSetMetaData.getAlias(CloudSpannerResultSetMetaData.java:384)
	at nl.topicus.jdbc.resultset.CloudSpannerResultSetMetaData.getColumnLabel(CloudSpannerResultSetMetaData.java:352)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.getColumnLabel(JDBCResultSetMetaDataImpl.java:153)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCColumnMetaData.<init>(JDBCColumnMetaData.java:89)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCColumnMetaData.<init>(JDBCColumnMetaData.java:69)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.createColumnMetaDataImpl(JDBCResultSetMetaDataImpl.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.<init>(JDBCResultSetMetaDataImpl.java:51)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCFactoryDefault.createResultSetMetaData(JDBCFactoryDefault.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.createMetaDataImpl(JDBCResultSetImpl.java:1682)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:228)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getMeta(JDBCResultSetImpl.java:1)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchStart(ResultSetDataReceiver.java:96)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.fetchQueryData(SQLQueryJob.java:673)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeStatement(SQLQueryJob.java:462)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.lambda$0(SQLQueryJob.java:389)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1539)
	... 8 more
```

Thanks :)

**Comment by olavloite** [comment]
Fixed for version 1.0.11

**Comment by flascaray** [comment]
Hi @olavloite. I'm trying the new release but I have a similar exception.

```java
Caused by: java.lang.NullPointerException
	at nl.topicus.jdbc.resultset.CloudSpannerResultSetMetaData.getColumn(CloudSpannerResultSetMetaData.java:379)
	at nl.topicus.jdbc.resultset.CloudSpannerResultSetMetaData.getColumnName(CloudSpannerResultSetMetaData.java:364)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.getColumnName(JDBCResultSetMetaDataImpl.java:160)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCColumnMetaData.<init>(JDBCColumnMetaData.java:90)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCColumnMetaData.<init>(JDBCColumnMetaData.java:69)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.createColumnMetaDataImpl(JDBCResultSetMetaDataImpl.java:57)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetMetaDataImpl.<init>(JDBCResultSetMetaDataImpl.java:51)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCFactoryDefault.createResultSetMetaData(JDBCFactoryDefault.java:58)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.createMetaDataImpl(JDBCResultSetImpl.java:1682)
```

**Comment by olavloite** [comment]
Hi @flascaray , the problem occurs because the query contains a part (`INTERVAL interval HOUR`) that is not understood by the SQL parser that is used by the jdbc driver. That is normally not a problem and just ignored by the driver, except when the resultset metadata of the query is required, as the driver in that case also tries to parse the query in order to identify the columns, tables etc. in the query. The driver did not contain enough safeguards to gracefully degrade in those cases. I hope that with this last change, all those problems should now be solved.

**Comment by flascaray** [comment]
Ok @olavloite i will try to build the branch and tell you if it works. Thanks.
